In [69]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [70]:
dataset = pd.read_csv("C:\\Users\\jalad\\Downloads\\winequalityN.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [71]:
print(X)

[['white' 7.0 0.27 ... 3.0 0.45 8.8]
 ['white' 6.3 0.3 ... 3.3 0.49 9.5]
 ['white' 8.1 0.28 ... 3.26 0.44 10.1]
 ...
 ['red' 6.3 0.51 ... 3.42 0.75 11.0]
 ['red' 5.9 0.645 ... 3.57 0.71 10.2]
 ['red' 6.0 0.31 ... 3.39 0.66 11.0]]


In [72]:
print(y)

[6 6 6 ... 6 5 6]


In [73]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:12])
X[:, 1:12] = imputer.transform(X[:, 1:12])

In [74]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [75]:
print(X)

[[0.0 1.0 7.0 ... 3.0 0.45 8.8]
 [0.0 1.0 6.3 ... 3.3 0.49 9.5]
 [0.0 1.0 8.1 ... 3.26 0.44 10.1]
 ...
 [1.0 0.0 6.3 ... 3.42 0.75 11.0]
 [1.0 0.0 5.9 ... 3.57 0.71 10.2]
 [1.0 0.0 6.0 ... 3.39 0.66 11.0]]


In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.8, random_state = 1)

In [77]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [78]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [79]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[6.26 6.  ]
 [6.11 7.  ]
 [5.65 5.  ]
 ...
 [6.62 7.  ]
 [5.83 6.  ]
 [5.93 6.  ]]


In [80]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.2947797206457935