# House Price Prediction

## Importing the Libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading the Dataset

In [4]:
dataset=pd.read_csv("C:\\Users\\jalad\\Downloads\\Housing.csv")
X=dataset.iloc[:,1:].values
Y=dataset.iloc[:,0].values

In [5]:
print(X)

[[7420 4 2 ... 2 'yes' 'furnished']
 [8960 4 4 ... 3 'no' 'furnished']
 [9960 3 2 ... 2 'yes' 'semi-furnished']
 ...
 [3620 2 1 ... 0 'no' 'unfurnished']
 [2910 3 1 ... 0 'no' 'furnished']
 [3850 3 1 ... 0 'no' 'unfurnished']]


In [6]:
print(Y)

[13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  6615000  6580000  6510000  6510000  6510000  6475000
  6475000  6440000  6440000  6419000  6405000  6300000  6300000  6300000
  6300000  6300000  6293000  6265000  6230000  6230000  6195000  6195000
  6195000  6160000  6160000  6125000  6107500  6090

## Applying Label encoding to categorical data

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
col=[4,5,6,7,8,10]
for i in col:
    X[:,i]=le.fit_transform(X[:,i])

## Applying OneHot Encoding to Categorical data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [11])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 2 1]
 [1.0 0.0 0.0 ... 1 3 0]
 [0.0 1.0 0.0 ... 0 2 1]
 ...
 [0.0 0.0 1.0 ... 0 0 0]
 [1.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 1.0 ... 0 0 0]]


## Splitting the Dataset into Train and Test sets

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [11]:
print(X_train)

[[0.0 0.0 1.0 ... 0 0 0]
 [0.0 0.0 1.0 ... 0 0 0]
 [0.0 0.0 1.0 ... 0 0 0]
 ...
 [0.0 0.0 1.0 ... 1 1 1]
 [0.0 0.0 1.0 ... 0 1 0]
 [1.0 0.0 0.0 ... 0 0 1]]


In [12]:
print(Y_train)

[ 1750000  2695000  2870000  2590000  4515000  4410000  4585000  5250000
  3570000  3640000  9800000  2940000  6083000  3255000  4893000  3150000
  2975000  6930000  3500000  5880000  3500000  4235000  3710000  4060000
  2345000  4550000 10150000  3640000  2660000  2233000  2135000  4277000
  6230000  6300000  3920000  7350000  8400000  5215000  7420000  6230000
  4900000  4550000  4060000  3010000  7343000  5600000  7140000 10150000
  9870000  3780000  2940000  2653000  3836000  4760000  7962500  3143000
  3500000  4690000  4340000  4515000  1767150  3080000  5950000  5530000
  3150000  7210000  2800000  3045000  2835000  1820000  3465000  4200000
  5040000  7350000  5250000  4690000  4900000  5495000  1750000  8120000
  3675000  8890000  3920000  4550000  2275000  7350000  6650000  8463000
  5250000  6405000  5285000 11410000  2604000  5215000  4550000  3010000
 10850000  5652500  3850000  4900000  5775000  2940000  5950000  8645000
  6860000  4900000  8750000  2653000  3605000  9240

In [13]:
print(X_test)

[[1.0 0.0 0.0 ... 0 1 0]
 [1.0 0.0 0.0 ... 0 2 1]
 [0.0 1.0 0.0 ... 1 0 0]
 ...
 [0.0 1.0 0.0 ... 0 1 0]
 [0.0 1.0 0.0 ... 0 1 0]
 [1.0 0.0 0.0 ... 0 2 1]]


In [14]:
print(Y_test)

[ 4585000  6083000  4007500  6930000  2940000  6195000  3535000  2940000
  3500000  7980000  6755000  3990000  3150000  3290000  4130000  2660000
  4410000  3710000  3360000  4270000  5005000  5383000  6440000  1890000
  6125000  5460000  5803000  4620000  5530000  5950000  4305000  3640000
  5250000  3325000  3703000  4753000  9100000  3500000  3150000  4270000
  8960000  4060000  5740000  3129000  3633000  7560000  4620000  3290000
  4165000  6650000  4165000  4690000  3150000  3850000  3290000  5075000
  6510000  5740000  3780000  4795000  4900000  5460000  3500000  7525000
  2835000  5495000  8680000  4200000  4200000  4900000  3332000  6195000
  4098500  6650000  3885000  4620000  1960000  6440000  1750000  3605000
  3290000  4970000  4613000  3850000  3500000  6107500  3780000  4900000
  3570000  4340000  3500000  6300000  3395000  3815000  3920000 12250000
  3080000  9310000  4270000  3780000  5600000  3290000  2380000  5110000
  6650000  5810000  4123000  3080000  5530000]


## Applying the feature scaling

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Traing the model on dataset using Regression

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression()

In [17]:
Y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[ 3950288.62  4585000.  ]
 [ 6173868.82  6083000.  ]
 [ 4483635.99  4007500.  ]
 [ 7258732.75  6930000.  ]
 [ 2836727.58  2940000.  ]
 [ 7032947.1   6195000.  ]
 [ 3203851.47  3535000.  ]
 [ 3270994.01  2940000.  ]
 [ 3472554.04  3500000.  ]
 [ 8289978.33  7980000.  ]
 [ 6605321.63  6755000.  ]
 [ 3723366.24  3990000.  ]
 [ 3812376.96  3150000.  ]
 [ 4548966.85  3290000.  ]
 [ 4020476.35  4130000.  ]
 [ 1969836.22  2660000.  ]
 [ 4057262.98  4410000.  ]
 [ 3704586.87  3710000.  ]
 [ 3282767.93  3360000.  ]
 [ 4609423.65  4270000.  ]
 [ 5968243.74  5005000.  ]
 [ 6363698.62  5383000.  ]
 [ 4751300.32  6440000.  ]
 [ 2659595.28  1890000.  ]
 [ 5305573.25  6125000.  ]
 [ 5680819.59  5460000.  ]
 [ 5404106.9   5803000.  ]
 [ 5543050.52  4620000.  ]
 [ 5768360.48  5530000.  ]
 [ 5801753.71  5950000.  ]
 [ 3389277.96  4305000.  ]
 [ 6399092.03  3640000.  ]
 [ 7081030.31  5250000.  ]
 [ 2913042.4   3325000.  ]
 [ 4498664.01  3703000.  ]
 [ 5210561.68  4753000.  ]
 [ 5013457.84  9100000.  ]
 

## Evaluating model performance

In [138]:
from sklearn.metrics import r2_score
r2_score(Y_test, Y_pred)

0.6611214250980104